### ISSUE TITLE
FixDecals doesn't work when creating custom preset cars using Binary.

### ISSUE THREAD

**Issue by jaigitrep159** [ArchieGoldmill/NFSC_ExtendedCustomizationV3#2]
```ini
FixDecals = 1 // Decal texture is now defiend by TEXTURE_NAME rather then part name
```
according to this, it is defined as a TEXTURE_NAME rather then part name.

but when i do it for creating custom preset cars according to that line in ini file, it didn't work.
I had to use the part name than texture name and it fixed. This is kinda a lie but it's a bug.

Tested using NFSC 1.4 Collectors Edition.

**Comment by ArchieGoldmill** [comment]
This change is related to db model part of decal, so you can add TEXTURE_NAME attribute to it that defines the texture to be used, in presets you still need to use part name
